### ISSUE TITLE
Infografía  de gestion de proyectos -Edwin Ortiz Cruz

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-EdwinOrtiz1412#2]
[Infografia gestion de Proyectos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-EdwinOrtiz1412/files/12457874/Infografia.gestion.de.Proyectos.pdf)

**Comment by abicoronel** [comment]
20% <3

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
